name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y g++ make

      - name: Build
        run: make

      - name: Run unit tests
        run: ./restapic --test u

      - name: Run integration tests
        run: ./restapic --test i

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install make

      - name: Build
        run: make

      - name: Run unit tests
        run: .\restapic.exe --test u

      - name: Run integration tests
        run: .\restapic.exe --test i