name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows-7:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install make

      - name: Build
        run: make

      - name: Run unit tests
        run: .\restapic.exe --test u

      - name: Run integration tests
        run: .\restapic.exe --test i

  build-windows-10:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install make

      - name: Build
        run: make

      - name: Run unit tests
        run: .\restapic.exe --test u

      - name: Run integration tests
        run: .\restapic.exe --test i

  build-windows-11:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install make

      - name: Build
        run: make

      - name: Run unit tests
        run: .\restapic.exe --test u

      - name: Run integration tests
        run: .\restapic.exe --test i